steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/pathan-artifact-repo/pathan-app:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/pathan-artifact-repo/pathan-app:latest']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'run'
      - 'deploy'
      - 'pathan-service'
      - '--image'
      - 'northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/pathan-artifact-repo/pathan-app:latest'
      - '--region'
      - 'northamerica-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
artifacts:
  objects:
    location: 'gs://pathan-codepipeline-bucket-$PROJECT_ID/'
    paths: ['imagedefinitions.json']
