AWSTemplateFormatVersion: '2010-09-09'
Description: Pathan Assignment 3 - AWS ECS Fargate Deployment with CI/CD

Parameters:
  GitHubOwner:
    Type: String
    Description: Your GitHub username
  GitHubRepo:
    Type: String
    Default: final
    Description: GitHub repository name
  GitHubBranch:
    Type: String
    Default: main
    Description: GitHub branch name
  GitHubToken:
    Type: String
    NoEcho: true
    Description: GitHub Personal Access Token (store in AWS Secrets Manager or provide manually)

Resources:
  # Add ECR Repository
  pathanECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: pathan-ecr
      ImageScanningConfiguration:
        ScanOnPush: true
      Tags:
        - Key: Name
          Value: pathan-ecr

  # Add S3 Bucket for CodePipeline Artifacts
  pathanCodePipelineBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub pathan-codepipeline-artifacts-${AWS::AccountId}
      VersioningConfiguration:
        Status: Enabled
        
  # --- VPC ---
  pathanVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: pathan-vpc

  pathanPublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref pathanVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: ca-central-1a
      Tags:
        - Key: Name
          Value: pathan-public-subnet-1

  pathanPublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref pathanVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: ca-central-1b
      Tags:
        - Key: Name
          Value: pathan-public-subnet-2

  pathanPrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref pathanVPC
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: ca-central-1a
      Tags:
        - Key: Name
          Value: pathan-private-subnet-1

  pathanPrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref pathanVPC
      CidrBlock: 10.0.4.0/24
      AvailabilityZone: ca-central-1b
      Tags:
        - Key: Name
          Value: pathan-private-subnet-2

  pathanInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: pathan-igw

  pathanVPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref pathanVPC
      InternetGatewayId: !Ref pathanInternetGateway

  pathanPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref pathanVPC
      Tags:
        - Key: Name
          Value: pathan-public-rt

  pathanPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: pathanVPCGatewayAttachment
    Properties:
      RouteTableId: !Ref pathanPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref pathanInternetGateway

  pathanPublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref pathanPublicSubnet1
      RouteTableId: !Ref pathanPublicRouteTable

  pathanPublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref pathanPublicSubnet2
      RouteTableId: !Ref pathanPublicRouteTable

  pathanPrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref pathanVPC
      Tags:
        - Key: Name
          Value: pathan-private-rt

  pathanNATGatewayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  pathanNATGateway:
    Type: AWS::EC2::NatGateway
    DependsOn: pathanVPCGatewayAttachment
    Properties:
      AllocationId: !GetAtt pathanNATGatewayEIP.AllocationId
      SubnetId: !Ref pathanPublicSubnet1
      Tags:
        - Key: Name
          Value: pathan-nat

  pathanPrivateRoute:
    Type: AWS::EC2::Route
    DependsOn: pathanNATGateway
    Properties:
      RouteTableId: !Ref pathanPrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref pathanNATGateway

  pathanPrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref pathanPrivateSubnet1
      RouteTableId: !Ref pathanPrivateRouteTable

  pathanPrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref pathanPrivateSubnet2
      RouteTableId: !Ref pathanPrivateRouteTable

  # --- Security Groups ---
  pathanALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for pathan ALB
      VpcId: !Ref pathanVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: pathan-alb-sg

  pathanECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for pathan ECS tasks
      VpcId: !Ref pathanVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          SourceSecurityGroupId: !Ref pathanALBSecurityGroup
      Tags:
        - Key: Name
          Value: pathan-ecs-sg

  # --- Application Load Balancer ---
  pathanLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    DependsOn:
      - pathanPublicSubnet1
      - pathanPublicSubnet2
    Properties:
      Name: pathan-alb
      Subnets:
        - !Ref pathanPublicSubnet1
        - !Ref pathanPublicSubnet2
      SecurityGroups:
        - !Ref pathanALBSecurityGroup
      Scheme: internet-facing
      Type: application

  pathanTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: pathan-tg
      Port: 5000
      Protocol: HTTP
      VpcId: !Ref pathanVPC
      TargetType: ip
      HealthCheckPath: /

  pathanListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - pathanLoadBalancer
      - pathanTargetGroup
    Properties:
      LoadBalancerArn: !Ref pathanLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref pathanTargetGroup

  # --- ECS Cluster ---
  pathanECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: pathan-ecs-cluster

  # --- ECS Task Definition ---
  pathanTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: pathan-task
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '256'
      Memory: '512'
      ExecutionRoleArn: !GetAtt pathanTaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: pathan-container
          Image: !Sub ${AWS::AccountId}.dkr.ecr.ca-central-1.amazonaws.com/pathan-ecr:latest
          PortMappings:
            - ContainerPort: 5000
          Essential: true

  pathanTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  # --- ECS Service (DesiredCount: 2) ---
  pathanECSService:
    Type: AWS::ECS::Service
    DependsOn:
      - pathanListener
      - pathanTaskDefinition
      - pathanTargetGroup
    Properties:
      Cluster: !Ref pathanECSCluster
      ServiceName: pathan-ecs-service
      TaskDefinition: !Ref pathanTaskDefinition
      DesiredCount: 2  # Two containers (Deliverable 7)
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !Ref pathanPrivateSubnet1
            - !Ref pathanPrivateSubnet2
          SecurityGroups:
            - !Ref pathanECSSecurityGroup
      LoadBalancers:
        - ContainerName: pathan-container
          ContainerPort: 5000
          TargetGroupArn: !Ref pathanTargetGroup
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100

  # --- Auto-Scaling (Updated Policy) ---
  pathanScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: pathanECSService
    Properties:
      MaxCapacity: 5  # Max 5 (Phase 3)
      MinCapacity: 2  # Min 2 to match DesiredCount
      ResourceId: !Sub service/${pathanECSCluster}/${pathanECSService.Name}
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  # Scale-Out Policy (CPU 90% for 2 minutes)
  pathanScaleOutPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: pathan-cpu-scale-out
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref pathanScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 90.0  # Scale out at 90% CPU (Phase 3)
        ScaleOutCooldown: 120  # 2 minutes
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization

  # Scale-In Policy (CPU below 50%)
  pathanScaleInPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: pathan-cpu-scale-in
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref pathanScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 50.0  # Scale in when below 50% (Phase 3)
        ScaleInCooldown: 120  # 2 minutes
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization

  # --- CodeBuild Role ---
  pathanCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: pathanCodeBuildPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:*
                  - logs:*
                  - s3:*
                Resource: '*'

  # --- CodeBuild Project ---
  pathanCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: pathan-codebuild
      ServiceRole: !GetAtt pathanCodeBuildRole.Arn
      Artifacts:
        Type: S3
        Location: !Sub pathan-codepipeline-artifacts-${AWS::AccountId}
        Name: BuildArtifact
        NamespaceType: NONE
        Packaging: ZIP
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        PrivilegedMode: true
      Source:
        Type: GITHUB
        Location: !Sub https://github.com/${GitHubOwner}/${GitHubRepo}.git
        BuildSpec: buildspec.yml  # Updated to match the file name

  # --- CodePipeline Role ---
  pathanCodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: pathanCodePipelinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - codebuild:*
                  - ecs:*
                  - s3:*
                  - iam:PassRole
                Resource: '*'

  # --- CodePipeline ---
  pathanCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    DependsOn:
      - pathanCodeBuildProject
      - pathanECSService
    Properties:
      RoleArn: !GetAtt pathanCodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Sub pathan-codepipeline-artifacts-${AWS::AccountId}
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubToken
        - Name: Approval
          Actions:
            - Name: ManualApproval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ProjectName: !Ref pathanCodeBuildProject
        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: ECS
                Version: '1'
              InputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ClusterName: !Ref pathanECSCluster
                ServiceName: !Ref pathanECSService
                FileName: imagedefinitions.json

Outputs:
  LoadBalancerURL:
    Description: URL of the Application Load Balancer
    Value: !Sub http://${pathanLoadBalancer.DNSName}